In [30]:
import pandas as pd
from sklearn import linear_model
import numpy as np

# Haciendolo con regresion lineal de sklearn

In [26]:

datos=pd.read_csv("est_quimico.csv")
print(datos)

    Experimento    x1    x2      y
0             1  41.9  29.1  251.3
1             2  43.4  29.3  251.3
2             3  43.9  29.5  248.3
3             4  44.5  29.7  267.5
4             5  47.3  29.9  273.0
5             6  47.5  30.3  276.5
6             7  47.9  30.5  270.3
7             8  50.2  30.7  274.9
8             9  52.8  30.8  285.0
9            10  53.2  30.9  290.0
10           11  56.7  31.5  297.0
11           12  57.0  31.7  302.5
12           13  63.5  31.9  304.5
13           14  64.3  32.0  309.3
14           15  71.1  32.1  321.7
15           16  77.0  32.5  330.7
16           17  77.8  32.9  349.0


In [27]:
y=datos["y"]
X=datos[["x1","x2"]]
rl=linear_model.LinearRegression().fit(X,y)

In [28]:
y_predic=rl.predict(X)

In [29]:
print(rl.intercept_)
print(rl.coef_)

-151.7579998249567
[ 1.25389314 12.00081181]


# Haciendolo a mano

In [62]:
idv=np.ones((datos.shape[0],1))

In [81]:
X=datos[["x1","x2"]].to_numpy()
X=np.hstack([idv,X])
Y=datos[["y"]].to_numpy()

In [82]:
beta=np.linalg.inv(X.T@X)@X.T@Y
beta

array([[-151.75799982],
       [   1.25389314],
       [  12.00081181]])

In [85]:
SSE=(Y.T@Y)-(beta.T@X.T@Y)
SSE

array([[413.01432921]])

In [87]:
varest=SSE/(Y.shape[0]-beta.shape[0])
varest

array([[29.50102352]])